// Home page layout.tsx
import MenuBar from './MenuBar'; // Import the Client Component
import '/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Common meta tags and links to stylesheets */}
      </head>
      <body>
        {/* Use the MenuBar component */}
        <MenuBar />
        {/* Page Content */}
        {children}
      </body>
    </html>
  );
}


